#!/usr/bin/env bash

MAIN_PID=-2
XVFB_PID=-2
AVCONV_PID=-2
DISABLE_XVFB=${DISABLE_XVFB:-0}
DISABLE_VIDEO=${DISABLE_VIDEO:-0}

# Set the default video name
VIDEO_NAME=${VIDEO_NAME:-}
if [ -z ${VIDEO_NAME} ]; then
  date=$(date -u "+%Y-%m-%d--%H:%M:%S")
  VIDEO_NAME="${BROWSER}-${date}"
fi

function main () {
  ensure-dirs-exist
  detect-bash "$@"
  load-entrypoint.d

  if [ $DISABLE_XVFB == 1 ]; then
    #echo "XVFB disabled"
    exec "$@"
  else
    start-xvfb
    if [ ! $DISABLE_VIDEO == 1 ]; then
      start-avconv
    fi

    trap teardown SIGTERM SIGINT
    "$@" &
    MAIN_PID=$!
    wait $MAIN_PID
    teardown
  fi
}

function teardown () {
  kill-avconv
  convert-video-to-mp4
  kill-xvfb
  kill-main
}

function ensure-dirs-exist () {
  mkdir -p \
      /app-tests/test-output \
      /app-tests/videos
}

function detect-bash () {
  if [ $1 == "bash" ]; then
    #echo "bash detected"
    DISABLE_XVFB="1"
  fi
}

function load-entrypoint.d () {
  if [ -d /docker-entrypoint.d ]; then
    for f in /docker-entrypoint.d/*.sh; do
      [ -f "$f" ] && . "$f"
    done
  fi
}

function start-xvfb () {
  Xvfb ${DISPLAY} \
      -screen 0 ${SCREEN_WIDTH}x${SCREEN_HEIGHT}x${SCREEN_DEPTH} \
      -ac \
      +extension RANDR &
  XVFB_PID=$!
}

function kill-xvfb () {
  kill $XVFB_PID
  wait $XVFB_PID
  XVFB_PID=-2
}

function start-avconv () {
  avconv -f x11grab \
      -loglevel error \
      -r 25 \
      -s ${SCREEN_WIDTH}x${SCREEN_HEIGHT} \
      -i ${DISPLAY}+0,0 \
      "/app-tests/videos/${VIDEO_NAME}.mkv" &
  AVCONV_PID=$!
}

function kill-avconv () {
  kill $AVCONV_PID
  wait $AVCONV_PID
  AVCONV_PID=-2
}

function convert-video-to-mp4 () {
  if [ ! -f "/app-tests/videos/${VIDEO_NAME}.mkv" ]; then
    return
  fi

  avconv \
      -loglevel error \
      -i "/app-tests/videos/${VIDEO_NAME}.mkv" \
      -codec copy \
      "/app-tests/videos/${VIDEO_NAME}.mp4"
  rm "/app-tests/videos/${VIDEO_NAME}.mkv"
}

function kill-main () {
  kill $MAIN_PID
  wait $MAIN_PID
  exit $?
}

main "$@"
